"""init"

Revision ID: a8689bef47af
Revises:
Create Date: 2025-04-26 14:37:14.132261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8689bef47af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="categorystatus", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["category.id"], name=op.f("fk_category_parent_id_category")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("name", name=op.f("uq_category_name")),
    )
    op.create_table(
        "spec",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("NUM", "STR", name="spectype", native_enum=False),
            nullable=False,
        ),
        sa.Column("units", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("filterable", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name=op.f("fk_spec_category_id_category")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spec")),
        sa.UniqueConstraint("category_id", "label", name=op.f("uq_spec_category_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spec")
    op.drop_table("category")
    # ### end Alembic commands ###
